In [4]:
import numpy
# Two matrices are initialized by value
x = numpy.array([[1, 5], [6, 8]])
y = numpy.array([[2, 8], [5, 10]])

#  add()is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))

# subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))

# divide()is used to divide matrices
print ("Matrix Division : ")
print (numpy.divide(x,y))

print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))
print ("The product of two matrices : ")
print (numpy.dot(x,y))

print ("square root is : ")
print (numpy.sqrt(x))

print ("The summation of elements : ")
print (numpy.sum(y))

print ("The column wise summation  : ")
print (numpy.sum(y,axis=0))

print ("The row wise summation: ")
print (numpy.sum(y,axis=1))

# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

Addition of two matrices: 
[[ 3 13]
 [11 18]]
Subtraction of two matrices : 
[[-1 -3]
 [ 1 -2]]
Matrix Division : 
[[0.5   0.625]
 [1.2   0.8  ]]
Multiplication of two matrices: 
[[ 2 40]
 [30 80]]
The product of two matrices : 
[[ 27  58]
 [ 52 128]]
square root is : 
[[1.         2.23606798]
 [2.44948974 2.82842712]]
The summation of elements : 
25
The column wise summation  : 
[ 7 18]
The row wise summation: 
[10 15]
Matrix transposition : 
[[1 6]
 [5 8]]
